### ISSUE TITLE
How to train rectangular datasets? 

### ISSUE THREAD

**Issue by pavelxx1** [Lornatang/UGATIT-PyTorch#3]
Q1:How to train rectangular datasets? 
Q2:
I want check test_video.py and have error
```
/content/UGATIT-PyTorch
Namespace(cuda=True, file='/content/drive/My Drive/abonent.mp4', image_size=200, manualSeed=None, model_name='selfie2anime')
Random Seed:  3486
[processing video and saving result videos]:   0% 0/18053 [00:00<?, ?it/s]fwe
Traceback (most recent call last):
  File "test_video.py", line 92, in <module>
    image = pre_process(frame).unsqueeze(0)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 244, in __call__
    return F.resize(img, self.size, self.interpolation)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py", line 319, in resize
    raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
TypeError: img should be PIL Image. Got <class 'numpy.ndarray'>
[processing video and saving result videos]:   0% 0/18053 [00:00<?, ?it/s]
```
Thx!

**Comment by Lornatang** [comment]
Oh, my previous test video file is wrong, I will update it as soon as possible!
